import numpy as np
import matplotlib.pyplot as plt

# 1. Configuration for your specific frame
WIDTH = 640
HEIGHT = 480
TOTAL_PIXELS = WIDTH * HEIGHT

pixels = []

print("Reading output_frame.hex...")

# 2. Read the hex file generated by Vivado
try:
    with open('output_frame.hex', 'r') as f:
        for line in f:
            line = line.strip()
            # Ignore empty lines and Verilog comments (e.g., // Addr ...)
            if not line or line.startswith('//'):
                continue
            
            # Convert the 32-bit Hex string to an Integer [1]
            # This represents the number of iterations it took to escape
            iteration_count = int(line, 16)
            pixels.append(iteration_count)
except FileNotFoundError:
    print("Error: output_frame.hex not found. Make sure it is in the same folder as this script.")
    exit()

# Safety check: ensure we have the correct number of pixels
if len(pixels) < TOTAL_PIXELS:
    print(f"Warning: Expected {TOTAL_PIXELS} pixels, got {len(pixels)}. Padding with zeros.")
    pixels.extend( * (TOTAL_PIXELS - len(pixels)))
elif len(pixels) > TOTAL_PIXELS:
    # Trim to exactly 64x48 if Vivado dumped extra memory addresses
    pixels = pixels[:TOTAL_PIXELS]

# 3. Reshape the 1D list into a 480x640 2D Numpy grid [2]
image_data = np.array(pixels).reshape((HEIGHT, WIDTH))

print("Rendering image...")

# 4. Plot the Image using Matplotlib [3]
plt.figure(figsize=(12, 9))

# plt.imshow displays the 2D array as an image. 
# 'magma' is a great colormap for fractals, mapping low iterations to dark colors and high to bright.
plt.imshow(image_data, cmap='magma', interpolation='nearest')

# Add a colorbar on the side to show what iteration count each color represents [4]
plt.colorbar(label='Iterations to Escape')
plt.title('Custom GPU Rendered Mandelbrot Set (640x480)')
plt.axis('off') # Hide the X/Y axes ticks for a cleaner look

# Display the window!
plt.show()
